
## 2 Monitor Config

# set $monitor1 DP-0
# set $monitor2 DP-1

## Workspaces 1-3 on monitor 1

# workspace 1 output $monitor1
# workspace 2 output $monitor1
# workspace 3 output $monitor1

## Workspaces 4-10 on monitor 2

# workspace 4 output $monitor2
# workspace 5 output $monitor2
# workspace 6 output $monitor2
# workspace 7 output $monitor2
# workspace 8 output $monitor2
# workspace 9 output $monitor2
# workspace 10 output $monitor2
